repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        language: system
        entry: sh -c 'cd kube-pilot && go fmt ./...'
        types: [go]
        pass_filenames: true

      - id: go-vet
        name: go vet
        language: system
        entry: sh -c 'cd kube-pilot && go vet ./...'
        pass_filenames: false
        types: [go]
